create extension if not exists vector;

-- 既存3072次元環境用。既定の768次元で新規作成する場合は vector(768) に変更する。

create table if not exists public.rag_documents (
  id bigint generated by default as identity primary key,
  source text not null,
  chunk_index integer not null,
  page_number integer not null,
  metadata jsonb not null default '{}'::jsonb,
  content text not null,
  content_hash text not null unique,
  embedding vector(3072) not null,
  created_at timestamptz not null default now()
);

create index if not exists rag_documents_embedding_idx
  on public.rag_documents using hnsw (embedding vector_cosine_ops);
